"""initial schema

Revision ID: 7f9bc7cad289
Revises: 
Create Date: 2026-04-25 10:04:39.269550
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f9bc7cad289'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('resource_type', sa.String(length=128), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_event_type'), 'audit_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_audit_log_resource_id'), 'audit_log', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('classification_labels',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color_key', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('connectors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('connector_type', sa.String(length=64), nullable=False),
    sa.Column('config_encrypted', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connectors_connector_type'), 'connectors', ['connector_type'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('policy_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('last_run_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_created_by_id'), 'policies', ['created_by_id'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_ids', sa.JSON(), nullable=False),
    sa.Column('scan_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('assets_scanned', sa.Integer(), nullable=False),
    sa.Column('columns_scanned', sa.Integer(), nullable=False),
    sa.Column('dq_issues_raised', sa.Integer(), nullable=False),
    sa.Column('policies_applied', sa.Integer(), nullable=False),
    sa.Column('schedule_cron', sa.String(length=128), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('connector_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_path', sa.String(length=512), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('schema_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('classifications', sa.JSON(), nullable=False),
    sa.Column('dq_score', sa.Float(), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('last_scanned_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_connector_id'), 'assets', ['connector_id'], unique=False)
    op.create_index(op.f('ix_assets_deleted_at'), 'assets', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_assets_name'), 'assets', ['name'], unique=False)
    op.create_index(op.f('ix_assets_owner_id'), 'assets', ['owner_id'], unique=False)
    op.create_index(op.f('ix_assets_schema_name'), 'assets', ['schema_name'], unique=False)
    op.create_index(op.f('ix_assets_source_path'), 'assets', ['source_path'], unique=False)
    op.create_table('glossary_terms',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('term', sa.String(length=255), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('synonyms', sa.JSON(), nullable=False),
    sa.Column('related_term_ids', sa.JSON(), nullable=False),
    sa.Column('linked_asset_ids', sa.JSON(), nullable=False),
    sa.Column('linked_column_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('steward_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['steward_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glossary_terms_term'), 'glossary_terms', ['term'], unique=True)
    op.create_table('columns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_type', sa.String(length=128), nullable=False),
    sa.Column('ordinal_position', sa.Integer(), nullable=False),
    sa.Column('nullable', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('classifications', sa.JSON(), nullable=False),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('uniqueness_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('accuracy_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_columns_asset_id'), 'columns', ['asset_id'], unique=False)
    op.create_index(op.f('ix_columns_name'), 'columns', ['name'], unique=False)
    op.create_table('lineage_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('upstream_asset_id', sa.String(length=36), nullable=False),
    sa.Column('downstream_asset_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['downstream_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['upstream_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineage_edges_downstream_asset_id'), 'lineage_edges', ['downstream_asset_id'], unique=False)
    op.create_index(op.f('ix_lineage_edges_upstream_asset_id'), 'lineage_edges', ['upstream_asset_id'], unique=False)
    op.create_table('dq_issues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('column_id', sa.String(length=36), nullable=True),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('delta_value', sa.Float(), nullable=True),
    sa.Column('current_score', sa.Float(), nullable=True),
    sa.Column('previous_score', sa.Float(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['column_id'], ['columns.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dq_issues_asset_id'), 'dq_issues', ['asset_id'], unique=False)
    op.create_index(op.f('ix_dq_issues_column_id'), 'dq_issues', ['column_id'], unique=False)
    op.create_index(op.f('ix_dq_issues_status'), 'dq_issues', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dq_issues_status'), table_name='dq_issues')
    op.drop_index(op.f('ix_dq_issues_column_id'), table_name='dq_issues')
    op.drop_index(op.f('ix_dq_issues_asset_id'), table_name='dq_issues')
    op.drop_table('dq_issues')
    op.drop_index(op.f('ix_lineage_edges_upstream_asset_id'), table_name='lineage_edges')
    op.drop_index(op.f('ix_lineage_edges_downstream_asset_id'), table_name='lineage_edges')
    op.drop_table('lineage_edges')
    op.drop_index(op.f('ix_columns_name'), table_name='columns')
    op.drop_index(op.f('ix_columns_asset_id'), table_name='columns')
    op.drop_table('columns')
    op.drop_index(op.f('ix_glossary_terms_term'), table_name='glossary_terms')
    op.drop_table('glossary_terms')
    op.drop_index(op.f('ix_assets_source_path'), table_name='assets')
    op.drop_index(op.f('ix_assets_schema_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_owner_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_name'), table_name='assets')
    op.drop_index(op.f('ix_assets_deleted_at'), table_name='assets')
    op.drop_index(op.f('ix_assets_connector_id'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('scans')
    op.drop_index(op.f('ix_policies_created_by_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_connectors_connector_type'), table_name='connectors')
    op.drop_table('connectors')
    op.drop_table('classification_labels')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_resource_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_event_type'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###

